import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { decodeBase64 } from "../../core/base64.js";
import { HASH_PLACEHOLDER } from "../../core/constants.js";
import { computeHash, computeHashBytes } from "../../core/hash.js";
import type { HashAlgorithm, Manifest } from "../../core/types.js";
import * as yaml from "../../core/yaml.js";

const TEXT_ENCODER = new TextEncoder();

export interface FinalizeArgs {
	file: string;
}

/**
 * Finalize an archive by computing real hashes for HASH_PLACEHOLDER values.
 * Useful for archives generated by AI assistants that can't compute hashes.
 */
export async function runFinalize(args: FinalizeArgs): Promise<void> {
	const filePath = resolve(args.file);
	const content = readFileSync(filePath, "utf-8");

	// Parse the archive
	let input = content;
	let headerComment = "";

	if (input.startsWith("<!--")) {
		const commentEnd = input.indexOf("-->");
		if (commentEnd !== -1) {
			headerComment = input.slice(0, commentEnd + 3);
			input = input.slice(commentEnd + 3).trimStart();
		}
	}

	if (!input.startsWith("---")) {
		console.error("Invalid archive: missing YAML frontmatter");
		process.exit(1);
	}

	const secondDelim = input.indexOf("\n---", 3);
	if (secondDelim === -1) {
		console.error("Invalid archive: missing closing --- delimiter");
		process.exit(1);
	}

	const yamlStr = input.slice(4, secondDelim);
	const afterFrontmatter = input.slice(secondDelim + 4);
	const contentSection = afterFrontmatter.replace(/^\n+/, "");

	const manifest = yaml.load(yamlStr) as Manifest;
	const algorithm: HashAlgorithm = manifest.mdmeld.hash_algorithm ?? "xxh64";

	let changed = false;

	// Compute file hashes
	const fence = "`".repeat(manifest.mdmeld.backtick_count);
	const pattern = new RegExp(
		`### (.+?)\\s*\\n\\s*${fence}([^\\n]*)\\n([\\s\\S]*?)\\n?${fence}(?=\\s|$)`,
		"g",
	);

	for (const match of contentSection.matchAll(pattern)) {
		const path = match[1]!.trim();
		const lang = match[2]!.trim();
		const rawContent = match[3]!;

		const entry = manifest.mdmeld.files.find((f) => f.path === path);
		if (entry && entry.hash === HASH_PLACEHOLDER) {
			// File hash is computed on original bytes (per spec)
			const isEncoded = lang === "base64" || entry.encoding === "base64";
			const bytes = isEncoded ? decodeBase64(rawContent) : TEXT_ENCODER.encode(rawContent);
			entry.hash = await computeHashBytes(bytes, algorithm);
			changed = true;
		}
	}

	// Compute content hash (on raw content after closing ---, per spec)
	if (manifest.integrity.content_hash === HASH_PLACEHOLDER) {
		manifest.integrity.content_hash = await computeHash(afterFrontmatter, algorithm);
		changed = true;
	}

	// Compute manifest hash (must be last, after all other manifest changes)
	if (manifest.integrity.manifest_hash === HASH_PLACEHOLDER) {
		// Manifest hash includes the `mdmeld:` key line per spec
		const manifestYaml = yaml.dump({ mdmeld: manifest.mdmeld });
		manifest.integrity.manifest_hash = await computeHash(manifestYaml, algorithm);
		changed = true;
	}

	if (!changed) {
		console.log("No HASH_PLACEHOLDER values found — archive already finalized");
		return;
	}

	// Re-serialize
	const outputYaml = yaml.dump(manifest);
	const prefix = headerComment ? `${headerComment}\n` : "";
	const output = `${prefix}---\n${outputYaml}---\n${afterFrontmatter}`;

	writeFileSync(filePath, output, "utf-8");
	console.log(`Finalized hashes in ${filePath}`);
}
